# DOCKER COMPOSE FOR THE WHOLE PROJECT

services:
  client:
    build: ./frontend
    container_name: chai-frontend
    ports:
      - 5173:3000
    restart: always
    networks:
      - chai-connection
    depends_on:
      - server

  server:
    build: ./backend
    container_name: chai-backend
    ports:
      - 8080:8080
    restart: always
    networks:
      - chai-connection

networks:
  chai-connection:
